# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cookie Wall for WordPress
subtitle: bot friendly
description:
  The Cookie Wall for WordPress is a plugin to comply with the EU law. Instead of offering a way to
  continue browsing without cookies, which possibly means loss of income for publishers, this cookie
  wall only accepts a confirmation.
baseurl: "/ll-cookie-wall" # the subpath of your site, e.g. /blog
url: "http://level-level.github.io/ll-cookie-wall/" # the base hostname & protocol for your site
twitter_username: levellevel

# Build settings
markdown: kramdown

# Compress sass files to main.css
sass:
    style: compressed

collections:
  - features
  - steps